use_cuda: true
data_parallel: true
num_epochs: 90
output_dir: experiments/imagenet

model:
  name: efficientnet_b0
  num_classes: 1000

dataset:
  name: imagenet_dataloaders
  root: data
  batch_size: 128
  image_size: 224
  num_workers: 16

optimizer:
  name: TFRMSprop
  lr: 0.05
  alpha: 0.9
  momentum: 0.9
  eps: 1.e-3

scheduler:
  name: MultiStepLR
  milestones: [30, 60, 80]
  gamma: 0.1
